apiVersion: v2
# renovate: datasource=github-releases depName=node-red/node-red
appVersion: 4.1.4
description: Node-RED is low-code programming for event-driven applications
name: node-red
version: 1.2.10
kubeVersion: ">=1.16.0-0"
keywords:
  - node-red
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/node-red
icon: https://nodered.org/about/resources/media/node-red-icon-2.png
sources:
  - https://github.com/node-red/node-red-docker
  - https://github.com/egeback/charts/tree/master/charts/node-red
maintainers:
  - name: egeback
    email: marky@egeback.se
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 3.7.1
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update node-red to 4.1.2