---
apiVersion: v2
# renovate: datasource=github-releases depName=louislam/uptime-kuma
appVersion: 2.1.0
description: A fancy self-hosted monitoring tool for your websites and applications
name: uptime-kuma
version: 2.1.1
kubeVersion: ">=1.16.0-0"
keywords:
  - uptime-kuma
  - status
  - status-page
  - monitoring
home: https://github.com/egeback/helm-charts/tree/main/charts/uptime-kuma
icon: https://github.com/louislam/uptime-kuma/raw/master/public/icon.svg
sources:
  - https://github.com/louislam/uptime-kuma
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2
maintainers:
  - name: egeback
    email: marky@egeback.se
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Update application to 2.1.0"
