apiVersion: v2
# renovate: datasource=github-releases depName=esphome/esphome
appVersion: 2026.1.4
description: ESP Home helm package
name: esphome
version: 1.1.4
kubeVersion: ">=1.16.0-0"
keywords:
  - ESPHOME
home: https://github.com/egeback/helm-charts/tree/main/charts/esphome
icon: https://esphome.io/_images/logo.svg
sources:
  - https://github.com/esphome
maintainers:
  - name: Marky Egeb√§ck
    email: marky@egeback.com
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.1.2
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Updated ESP Home to 2025.12.2
